### ISSUE TITLE
Crawl paginated page with Fluid Widget Paginator without detailview

### ISSUE THREAD

**Issue by cdominpxp** [webcoast-dk/versatile-crawler#4]
Is it possible to crawl a page which has a list view (extbase) with the fluid widget paginator but without an detail view?
At the moment, only the first page is crawled and i can't find a way to index the other pages from the paginator widget (paramter: tx_extkey_pluginkey[widget_0][currentPage]=2).

**Comment by thommyhh** [comment]
Hi Christoph, actually it is not and I'm not sure, if there is a generic solutions to this. I would recommend you to add your own crawler type (e.g. "Paginated [news, events, ...]"). Then you place a crawler configuration of that type on the page with the pagination.

The crawler should extend the FrontendRequestCrawler. You need to implement the fillQueue method from QueueInterface. In the method you need to read the necessary settings from the plugin to determine how many pages there need to be indexed. Please take a look at the PageTree crawler lines 82 - 99 and 101 - 147 on how to add items to the index queue with the necessary data. Remember to add the default url (without pagination parameter) as well, because depending on the other configurations (page tree) the default page might not be indexed, if it has its own configuration. The next method you need to implement is buildQueryString, where you use the `data` from your queue item to build the necessary parameters like id, L, the pagination parameter and probably cHash.

I know the wiki is missing the developer documentation. I will add it soon. Until then, I hope my explanations will help you achieve the proper crawling of your page. Let me know if you need further assistance.

**Comment by cdominpxp** [comment]
Thanks for your super fast response - i'm already looking in the code to achieve this because your extension is the only one which is ready for Typo3 Version 8 and it works with some tweaks already in live environment.

**Comment by thommyhh** [comment]
Nice to hear. What tweaks have you applied? Would be nice to know, so I can probably fix some things, that are not working as expected. Feel free to create a pull request, if you think the changes should be merged.

**Comment by cdominpxp** [comment]
There is already a reported [issue](https://github.com/webcoast-dk/versatile-crawler/issues/2) and i have made a fix but i don't think it is really the best way to do it.
IndexHook (Line 31ff):
```php
if ($request->getHeader(self::HASH_HEADER) != null && is_array($request->getHeader(self::HASH_HEADER)) && sizeof($request->getHeader(self::HASH_HEADER)) > 0) {
    $requestHeader = $request->getHeader(self::HASH_HEADER)[0];
} else {
    $requestHeader = $request->getHeader(self::HASH_HEADER);
   }
if ($request->hasHeader(self::HASH_HEADER) && strcmp($requestHeader, '') !== 0) {
```

**Comment by thommyhh** [comment]
Thank you. I will take a closer look.

**Comment by thommyhh** [comment]
@cdominpxp I needed to remove the whole request object thing, because instantiating the request twice, corrupted the $_FILES array. So I went the old way of iterating $_SERVER to find the correct header.

So, hopefully the 1.0.1 works without tweaks. Can you try it and provide feedback?
